
CMAKE_MINIMUM_REQUIRED(VERSION 2.8.7 FATAL_ERROR)

INCLUDE(FindPackageHandleStandardArgs)

FIND_LIBRARY(THC_LIBRARY THC)
FIND_PATH(THC_INCLUDE_DIR "THC.h" PATHS "${CMAKE_PREFIX_PATH}/include/THC")

SET(THC_LIBRARIES ${THC_LIBRARY})

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
  THC
  REQUIRED_ARGS
    THC_INCLUDE_DIR
    THC_LIBRARY)
