
CMAKE_MINIMUM_REQUIRED(VERSION 2.8.7 FATAL_ERROR)

INCLUDE(FindPackageHandleStandardArgs)

FIND_LIBRARY(THPP_LIBRARY thpp PATHS "${THPP_PREFIX_PATH}/thpp/build")
FIND_PATH(THPP_INCLUDE_DIR "thpp/Tensor.h" PATHS "${THPP_PREFIX_PATH}")

SET(THPP_LIBRARIES ${THPP_LIBRARY})

FIND_PACKAGE_HANDLE_STANDARD_ARGS(
  TH++
  REQUIRED_ARGS
    THPP_INCLUDE_DIR
    THPP_LIBRARY)

